### ISSUE TITLE
ربات هیدیفای

### ISSUE THREAD

**Issue by mehrdadtopme** [B3H1Z/Hiddify-Telegram-Bot#19]
سلام
من تست کردن ربات رو چند تا مطلب 

باید بگیم ادرس پنل همون ادرس ساب باشه چون بعضی ها مثل من سابشون فرق داره ادرسش

وضعیت اشتراک, اگر من چند تا وضعیت ( چند خرید با یک تلگرام) داشته باشم فقط وضعیت اولی رو میتونم جدا سازی کنم و بقیه امکانش نیست

امکان حذف گزینه ها باشه , مثلا من بتونم کیوار رو حذف کنم , بشه لینک راهنمای خودم رو در قسمت راهنما اضافه بکنم حداقل

در لیست پلن ها یک فاصله باشه بین عدد و گیگ , عدد و روز , عدد و تومان
و بشه هزار رو به تومان اضافه کرد مثال : 50 هزارتومان

و پلن هارو بشه زیبا تر کرد عالی میشه یا حداقل پلن 30 روز 60 روز
90 روز و ... بشه جداسازی بشه

وقتی پلن ها اضافه میشه ترتیب پلن ها به هم میریزه و گزینه ادیت پلن هم اضافه بشه

گزینه تمدید سرویس هم موجود نیست

 و در اخر سپاس از شما بابت زحماتتون ❤️

**Comment by B3H1Z** [comment]
سلام خدمت شما؛
1-ست کردن ادرس ساب هم هنگام کانفیگ کردن مشکلی به وجود نمی آورد
2-جداسازی تنها برای کانفیگ هایی هست که قبلا وجود داشتند و برای مدیریت به ربات لینک شده‌اند، نه کانفیگ هایی که مستقیم از ربات خریداری شده اند.
3-متاسفانه در حال حاضر امکان شخصی سازی در این درجه وجود ندارد، اما بخش راهنما در حال تکمیل شدن است و در آپدیت های بعدی قابلیت های شخصی سازی عرضه میشوند.
4-به علت کمبود فضا در دکمه ها این کار صورت کرفته، فرمتی که فرمودید رو در نظر خواهم گرفت
5-مشکل ترتیب در ورژن 5 که به زودی عرضه میشود حل خواهد شد
6- گزینه تمدید نیز در ورژن 5 افزوده شده
