### ISSUE TITLE
 انقضا 

### ISSUE THREAD

**Issue by mehrdadtopme** [B3H1Z/Hiddify-Telegram-Bot#25]
اگر بشه قبل تموم شدن یا پایان یافتن سرویس‌ پیام اتوماتیک بره که سرویس شما در حال اتمام هست یا پایان یافت هم خیلی خوبه

**Comment by mtashani** [comment]
این قابلیت رو داره ربات

**Comment by B3H1Z** [comment]
سلام، امکان اطلاع به کاربر در حال اتمام وجود داشت و در ورژن 5 قابل شخصی سازی است.
