### ISSUE TITLE
خرید اشتراک

### ISSUE THREAD

**Issue by mehrdadtopme** [B3H1Z/Hiddify-Telegram-Bot#29]
سلام
موقع خرید اشتراک حتما باید کیف پول رو شارژ کنیم 
خیلی خوب بود که هم پرداخت از کیف پول داشت هم خرید اشتراک
برای کاربران عادی الان خیلی سخت و گیج کننده هست

**Comment by mtashani** [comment]
> سلام موقع خرید اشتراک حتما باید کیف پول رو شارژ کنیم خیلی خوب بود که هم پرداخت از کیف پول داشت هم خرید اشتراک برای کاربران عادی الان خیلی سخت و گیج کننده هست

این قابلیت برای اینکه کاربر استقلال بیشتری داشته باشه و نیاز به تایید هر باره ادمین نداشته باشه برا خرید

**Comment by mehrdadtopme** [comment]
درسته ولی اگر جفتش باشه خیلی بهتره

**Comment by B3H1Z** [comment]
به علت اینکه در نهایت شیوه های دیگری برای پرداخت خواهیم داشت، کنترل این موضوع برای هرکدام، به دو شیوه مسقیم و افزودن به کیف پول دشوار و گمراه کننده است. در آینده پس از افزودن شیوه های پرداخت دیگر، اگر درخواست ها بالا باشد حتما روی این موضوع وقت خواهیم گذاشت.
