### ISSUE TITLE
اتصال چند پنل به یک بات

### ISSUE THREAD

**Issue by ahmad-79** [B3H1Z/Hiddify-Telegram-Bot#38]
سلام
یکی دو روزه دارم بات رو تست می‌کنم، بسیار کاربردی و پایدار بود.
کاستومایز کردن پیام‌ها هم بسیار راحت بود چون خیلی خوب پیادش کردین 
دست مریزاد

فقط خواستم اگر امکانش هست اضافه کردن اتصال چند پنل به یک بات رو در برنامه قرار بدید

من خودم سه تا پنل دارم که هر کدوم 100 تا کاربر داره تقریبا
این که سه تا بات داشته باشم و به هردسته کاربر یک کدومش رو بدم زیاد جالب نیست
اگه بشه هر سه تا پنل رو به ی بات متصل کرد که همه‌ی کاربرا بتونن اشتراکشون رو به بات متصل کنن و ازش استفاده کنن عالی میشه
میتونیم برای تعریف کاربرهای جدید هم ی حالت لود بلنسر شکلی اضافه کنیم که هر بار کاربر جدید رو تو یک پنل بسازه

**Comment by B3H1Z** [comment]
سلام
قابلیت مولتی پنل تقریبا تکمیل شده.
اگر دوست دارید زودتر امتحان کنید، میتونید نسخه pre-release رو نصب کنید. کامند و شرایط مربوطه در گروه تلگرامی قرار دارد.

**Comment by ahmad-79** [comment]
عالیه
تست میکنم حتما

ی چیز دیگه هم الان یادم اومد 
حتما ی silent restart هم اضافه کنید بشه بدون این که `ربات کاربران هیدی بات با موفقیت راه‌اندازی شد.
برای شروع کار، دستور /start را ارسال کنید.` برای کاربرها ارسال بشه restart کنیم

**Comment by B3H1Z** [comment]
تا جایی که بنده به یاد دارم پیام برای کاربران نمیره و در ربات کاربران هم فقط برای ادمین ارسال میشه

**Comment by ahmad-79** [comment]
چک کردم درسته
ایشو رو می‌بندم با اجازه
