### ISSUE TITLE
استفاده از چند سرور با یک لینک ربات

### ISSUE THREAD

**Issue by m0riii** [B3H1Z/Hiddify-Telegram-Bot#4]
ممنون از ربات خوب تون 
فقط اگر امکانش هست قابلیت اینکه بشه از یک ربات برای چند سرور استفاده کرد عالی میشه 
و نیازی نباشه که برای هر ربات یه لینک مخصوص به مشتری داده بشه و همشون وصل بشن به هم دیگه

**Comment by B3H1Z** [comment]
سلام خدمت شما؛
قابلیت ذکر شده بیشتر مرتبط به انتشار پنل مرکزی هیدیفای میباشد.
البته قابلیت اینکه بشود چند پنل را به یک ربات وصل کرد (که البته کار پر چالشی هست) قابل انجام است، اما این کار نیازمند انتشار API رسمی از طرف هیدیفای است.
در خال حاضر یک API از طرف هیدیفای منتشر شده، اما بنا بر گزارشات دارای باگ های متعددی هست و برخی از قابلیت ها را ندارد.
