### ISSUE TITLE
اضافه کردن عکس به بخش راهنما

### ISSUE THREAD

**Issue by m0riii** [B3H1Z/Hiddify-Telegram-Bot#5]
اگر امکانش هست قابلیت اضافه کردن عکس به بخش راهنما برای اینکه بشه عکس گذاشت که هر اپلیکشن به چه صورت باید تعریف بشه لینک اشتراک درون ش هم عالی میشه

**Comment by B3H1Z** [comment]
این تغییر را در آپدیت های بعدی در نظر داریم، اما قابلیت شخصی سازی مقداری دشوار است. بخش راهنما در آینده تغییرات زیادی میکند.
