### ISSUE TITLE
bug in hiddify database

### ISSUE THREAD

**Issue by sadjad1011001** [B3H1Z/Hiddify-Telegram-Bot#86]
does this script make change in hiddify databases?

it cause I think an issue that prevent hiddify panel from update

sr/local/lib/python3.10/dist-packages/hiddifypanel/panel/cli.py", line 50, in all_configs
    valid_users = [u.to_dict() for u in User.query.filter((User.usage_limit_GB > User.current_usage_GB)).all() if is_user_active(u)]
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/cli.py", line 50, in <listcomp>
    valid_users = [u.to_dict() for u in User.query.filter((User.usage_limit_GB > User.current_usage_GB)).all() if is_user_active(u)]
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/user.py", line 148, in to_dict
    'added_by_uuid': d.admin.uuid,

**Comment by B3H1Z** [comment]
We use the Hiddify api, and for this reason, you can also install the script on a third-party server, so we do not have access to the database. Please report Hiddify bugs on their GitHub.
